# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    continuationIndentSize: 8
  ParameterListWrapping:
    active: false
    indentSize: 8
  ImportOrdering:
    layout: 'ascii'
  MaximumLineLength:
    active: false

exceptions:
  TooGenericExceptionThrown:
    active: false
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false
  PrintStackTrace:
    active: false

style:
  MaxLineLength:
    active: false
    maxLineLength: 300
  MagicNumber:
    active: false
  LoopWithTooManyJumpStatements:
    maxJumpCount: 2

complexity:
  LongParameterList:
    ignoreDefaultParameters: true
    functionThreshold: 8
    constructorThreshold: 10

  NestedBlockDepth:
    threshold: 8
